/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AguaRouteImport } from './routes/agua'
import { Route as NutriRouteImport } from './routes/nutri'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as TreinoRouteImport } from './routes/treino'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AguaRoute = AguaRouteImport.update({
  id: '/agua',
  path: '/agua',
  getParentRoute: () => rootRouteImport,
} as any)
const NutriRoute = NutriRouteImport.update({
  id: '/nutri',
  path: '/nutri',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agua': typeof AguaRoute
  '/nutri': typeof NutriRoute
  '/perfil': typeof PerfilRoute
  '/treino': typeof TreinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agua': typeof AguaRoute
  '/nutri': typeof NutriRoute
  '/perfil': typeof PerfilRoute
  '/treino': typeof TreinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agua': typeof AguaRoute
  '/nutri': typeof NutriRoute
  '/perfil': typeof PerfilRoute
  '/treino': typeof TreinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agua' | '/nutri' | '/perfil' | '/treino'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agua' | '/nutri' | '/perfil' | '/treino'
  id: '__root__' | '/' | '/agua' | '/nutri' | '/perfil' | '/treino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AguaRoute: typeof AguaRoute
  NutriRoute: typeof NutriRoute
  PerfilRoute: typeof PerfilRoute
  TreinoRoute: typeof TreinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agua': {
      id: '/agua'
      path: '/agua'
      fullPath: '/agua'
      preLoaderRoute: typeof AguaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutri': {
      id: '/nutri'
      path: '/nutri'
      fullPath: '/nutri'
      preLoaderRoute: typeof NutriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AguaRoute: AguaRoute,
  NutriRoute: NutriRoute,
  PerfilRoute: PerfilRoute,
  TreinoRoute: TreinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
